### ISSUE TITLE
Similar Project

### ISSUE THREAD

**Issue by tooolbox** [Leeds-eBooks/Ebookama#1]
Hey there, I admire your work!  Very clean code and pretty well set-up.

Seems like we've been solving similar problems: https://github.com/allscribe/allscribe

Obviously we have significantly divergent codebases, but maybe we can learn something from each other.  Pardon if my docs aren't wonderfully in order :)

**Comment by benadamstyles** [comment]
Nice! Thanks for getting in touch. I am away from any computers for 2 weeks from tomorrow but when I am back I will take a look at your code. It would be cool to collaborate if we can. My dream would be to package ebookama up into an electron app and/or a proper cli.

**Comment by benadamstyles** [comment]
Allscribe package appears to have been removed, so I'm closing this issue.
